routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(["middleware" => 'auth'], function () {
//orland system
    Route::get('/dashboard', 'OrlandoController@dashboard')->name('dashboard');
    Route::get('/', 'OrlandoController@index')->name('home');
    Route::post('/payment', 'PaymentController@payment')->name('payment');
    Route::post('/import', 'OrlandoController@import')->name('import');
    Route::get('paymentdata', 'OrlandoController@paymentdata')->name('paymentdata');
    Route::get('/logs', 'LogController@index')->name('logs');
    Route::get('/getlogs', 'LogController@getlogs')->name('getlogs');
    Route::get('/orland', 'OrlandoController@edit')->name('editOrlando');
    Route::post('/updateOrlando', 'OrlandoController@update')->name('updateOrlando');
 //system Payment Logs
    Route::get('/payment','PaymentController@index')->name('paymentindex');
    Route::get('/paymentLogs','PaymentController@paymentLogs')->name('paymentLogs');
    Route::get('/makesecondpayment','PaymentController@makesecondpayment')->name('makesecondpayment');
//user system
    Route::resource('user', 'UserController');
    Route::resource('location', 'LocationController');
//    Route::get('/delete/{location}', 'LocationController@delete')->name('delete');
    Route::get('ajaxdata', 'LocationController@ajaxdata')->name('ajaxdata');
    Route::resource('form', 'FormController');
    Route::get('ajaxForms', 'FormController@ajaxForms')->name('ajaxForms');
    Route::get('ajaxUsers', 'UserController@ajaxUsers')->name('ajaxUsers');
    Route::get('userprofile', 'UserController@showProfile')->name('profileview');
    Route::post('profile', 'UserController@updateProfile')->name('updateProfile');
//settings for payment gateways
    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
//Roles system
    Route::resource('role', 'RoleController');
    Route::get('ajaxRole', 'RoleController@ajaxRole')->name('ajaxRole');
//permission system
    Route::resource('permission', 'PermissionController');
    Route::get('/ajaxPermission', 'PermissionController@ajaxPermission')->name('ajaxPermission');


    // payroll routes.. Added By Asad..
    Route::get('/payroll_import', 'payrollController@payroll_import')->name('payroll_import');
    Route::get('/visits_report', 'payrollController@visits_report')->name('visits_report');
    Route::post('/saveImportedVisitsReport', 'payrollController@import')->name('saveImportedVisitsReport');
    Route::get('ajaxVistsReport', 'payrollController@ajaxVistsReport')->name('ajaxVistsReport');
    Route::post('ajax_payroll_adjustments_save', 'payrollController@ajax_payroll_adjustments_save')->name('ajax_payroll_adjustments_save');
    Route::post('payViaPayPal', 'payrollController@payViaPayPal')->name('payViaPayPal');
    Route::post('payroll_adjustments_save', 'payrollController@payroll_adjustments_save')->name('payroll_adjustments_save');
    Route::post('ajaxApplyPayrollFilter', 'payrollController@ajaxApplyPayrollFilter')->name('ajaxApplyPayrollFilter');
    Route::get('/view_payroll/{id}', 'payrollController@view_payroll');
    Route::get('/employee_detail', 'payrollController@employee_detail')->name('employee_detail');
    Route::get('/view_payroll_details/{id}/{payroll_id?}', 'payrollController@view_payroll_details');
    Route::get('/paypal/complete_transaction/{fd}/{td}/{ei}/{pv}', 'payrollController@complete_transaction');
    Route::post('updatePayrollBankTransactionStatus', 'payrollController@updatePayrollBankTransactionStatus')->name('updatePayrollBankTransactionStatus');
});
Route::get('/payment/{token}','FormController@showAmount')->name('publicForm');
Auth::routes();

app/Permission.php
<?php
namespace App;

use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission
{
    public function users(){
        return $this->belongsToMany('App\User');
    }
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Location;
use Yajra\DataTables\DataTables;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $locations=Location::all();
        $user=Auth::user();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'View Permission Url', $user->location_id);
        if($isAllowed) {
            return view('permission.index');
        }else{
             return redirect(route('dashboard',compact('locations'))->with(['Message','You Dont have Permission to access']));
        }
    }
    public function ajaxPermission(Request $request)
    {
        $data = Permission::where('id', '>', 0);
        return DataTables::of($data)
            ->addColumn('function', function (Permission $permission) {
                return "<a href='".route( 'permission.edit',$permission->id) . "' id='edit'>
                        <button class='btn btn-primary' title='Edit' data-toggle='modal' data-target=''><i class='fa fa-edit'></i></button></a>" . view('permission.delete', compact('permission'))->render();
            })
            ->rawColumns(['function'])
            ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user=Auth::user();
        $locations=Location::all();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'Create Permission Url', $user->location_id);
        if($isAllowed) {
            return view('permission.create');
        }else{

            return redirect(route('dashboard',compact('locations')))->with(['Message','You Dont have Permission to access']);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $permission = new Permission();
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();
        return redirect()->back()->with(['message'=>'Permission Created Successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function show(Permission $permission)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        $locations=Location::all();
        $user=Auth::user();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'Edit Permission Url', $user->location_id);
        if($isAllowed) {
        return view('permission.edit',compact('permission'));
            }else{
            return redirect(route('dashboard',compact('locations')))->with(['Message','You Dont have Permission to access']);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();
        return redirect()->back()->with(['message'=>'Permission Updated Successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        $user=Auth::user();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'Delete Permission Url', $user->location_id);
        if($isAllowed) {
            $permission->delete();
            return redirect()->back()->with(['message' => 'Permission Deleted Successfully.']);
        }else{
            return redirect(route('dashboard',compact('locations')))->with(['Message','You Dont have Permission to access']);
        }

    }
}

resources/views/permission/create.blade.php
@extends('master')
@section('content')
    <div class="card">

        <div class="row">
            <div class="col-md-12">
                <div class="card bg-gray-light ">
                    <div class="card-header text-black anime">
                        <p class="text-black-50">Users Details</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            @if(session()->has('message'))
                                <div class="alert alert-success">
                                    {{ session()->get('message') }}
                                </div>
                            @endif
                            <form action="{{route('permission.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                <label>Name</label>
                                    <div class="col-md-6">
                                    <input class="form-control" name="name" type="text"  value="{{ old('name') }}">
                                </div>
                                </div>
                                <div class="form-group">
                                    <label>Display Name</label>
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" name="display_name" value="{{ old('display_name') }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" name="description" value="{{ old('description') }}">
                                    </div>
                                </div>
                                <input type="submit" name="Create New Role" class="btn btn-lg btn-primary">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/permission/delete.blade.php
<button class="btn btn-danger" onclick="frmdlt{{$permission->id}}.submit();"  title="Block"><i class="fa fa-ban"></i></button>
<form name="frmdlt{{$permission->id}}" action="{{ route('permission.destroy', $permission->id)}}" method="post">
    {!! method_field('delete') !!}
    {{csrf_field()}}
</form>

resources/views/permission/edit.blade.php
@extends('master')
@section('content')
    <div class="card">

        <div class="row">
            <div class="col-md-12">
                <div class="card bg-gray-light ">
                    <div class="card-header text-black anime">
                        <p class="text-black-50">Users Details</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            @if(session()->has('message'))
                                <div class="alert alert-success">
                                    {{ session()->get('message') }}
                                </div>
                            @endif
                            <form action="{{route('permission.update',$permission->id)}}" method="post" enctype="multipart/form-data">
                                @csrf
                                <input name="_method" type="hidden" value="PUT">

                                <div class="form-group">
                                    <label>Name</label>
                                    <div class="col-md-6">
                                        <input class="form-control" name="name" type="text"  value="{{ old('name',$permission->name) }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Display Name</label>
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" name="display_name" value="{{ old('display_name',$permission->display_name) }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" name="description" value="{{ old('description',$permission->description) }}">
                                    </div>
                                </div>
                                <input type="submit" name="Create New Role" class="btn btn-lg btn-primary">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/permission/index.blade.php
@extends('master')
@section('content')
    <div class="card">

        <div class="row">
            <div class="col-md-12">
                <div class="card bg-gray-light ">
                    <div class="card-header text-black anime">
                        <p class="text-black-50">Users Details</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="data"  class="table-striped"
                                   style="width: 100%;">
                                <thead>
                                <tr class="bg-pale-dark">
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Display Name</th>
                                    <th>Description</th>
                                    <th>Functions</th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('script')
    <script>
        var table;
        $(document).ready(function () {


            var methodes;
            table = $('#data').DataTable({
                dom: 'lBtip',
                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
                processing: true,
                serverSide: true,
                responsive: true,
                scrollX: true,
                ajax: {
                    url: '{{route('ajaxPermission')}}',
                },
                columns: [
                    {data: 'id', Title: 'id', orderable: false},
                    {data: 'name', Title: 'name', orderable: false},
                    {data: 'display_name', Title: 'display_name', orderable: false},
                    {data: 'description', Title: 'description', orderable: false},
                    {data: 'function', Title: 'function', orderable: false},
                ],
                "columnDefs": [

                    {
                        "targets": 0
                    },

                    {
                        "targets": 1
                    },
                    {

                        "targets": 2
                    },
                    {

                        "targets": 3
                    },
                    {

                        "targets": 4
                    }
                ],
            });
        });




    </script>
@endsection