routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(["middleware" => 'auth'], function () {
//orland system
    Route::get('/dashboard', 'OrlandoController@dashboard')->name('dashboard');
    Route::get('/', 'OrlandoController@index')->name('home');
    Route::post('/payment', 'PaymentController@payment')->name('payment');
    Route::post('/import', 'OrlandoController@import')->name('import');
    Route::get('paymentdata', 'OrlandoController@paymentdata')->name('paymentdata');
    Route::get('/logs', 'LogController@index')->name('logs');
    Route::get('/getlogs', 'LogController@getlogs')->name('getlogs');
    Route::get('/orland', 'OrlandoController@edit')->name('editOrlando');
    Route::post('/updateOrlando', 'OrlandoController@update')->name('updateOrlando');
 //system Payment Logs
    Route::get('/payment','PaymentController@index')->name('paymentindex');
    Route::get('/paymentLogs','PaymentController@paymentLogs')->name('paymentLogs');
    Route::get('/makesecondpayment','PaymentController@makesecondpayment')->name('makesecondpayment');
//user system
    Route::resource('user', 'UserController');
    Route::resource('location', 'LocationController');
//    Route::get('/delete/{location}', 'LocationController@delete')->name('delete');
    Route::get('ajaxdata', 'LocationController@ajaxdata')->name('ajaxdata');
    Route::resource('form', 'FormController');
    Route::get('ajaxForms', 'FormController@ajaxForms')->name('ajaxForms');
    Route::get('ajaxUsers', 'UserController@ajaxUsers')->name('ajaxUsers');
    Route::get('userprofile', 'UserController@showProfile')->name('profileview');
    Route::post('profile', 'UserController@updateProfile')->name('updateProfile');
//settings for payment gateways
    Route::get('/settings', 'SettingController@show')->name('settings.show');
    Route::post('/settings', 'SettingController@update')->name('settings.update');
//Roles system
    Route::resource('role', 'RoleController');
    Route::get('ajaxRole', 'RoleController@ajaxRole')->name('ajaxRole');
//permission system
    Route::resource('permission', 'PermissionController');
    Route::get('/ajaxPermission', 'PermissionController@ajaxPermission')->name('ajaxPermission');


    // payroll routes.. Added By Asad..
    Route::get('/payroll_import', 'payrollController@payroll_import')->name('payroll_import');
    Route::get('/visits_report', 'payrollController@visits_report')->name('visits_report');
    Route::post('/saveImportedVisitsReport', 'payrollController@import')->name('saveImportedVisitsReport');
    Route::get('ajaxVistsReport', 'payrollController@ajaxVistsReport')->name('ajaxVistsReport');
    Route::post('ajax_payroll_adjustments_save', 'payrollController@ajax_payroll_adjustments_save')->name('ajax_payroll_adjustments_save');
    Route::post('payViaPayPal', 'payrollController@payViaPayPal')->name('payViaPayPal');
    Route::post('payroll_adjustments_save', 'payrollController@payroll_adjustments_save')->name('payroll_adjustments_save');
    Route::post('ajaxApplyPayrollFilter', 'payrollController@ajaxApplyPayrollFilter')->name('ajaxApplyPayrollFilter');
    Route::get('/view_payroll/{id}', 'payrollController@view_payroll');
    Route::get('/employee_detail', 'payrollController@employee_detail')->name('employee_detail');
    Route::get('/view_payroll_details/{id}/{payroll_id?}', 'payrollController@view_payroll_details');
    Route::get('/paypal/complete_transaction/{fd}/{td}/{ei}/{pv}', 'payrollController@complete_transaction');
    Route::post('updatePayrollBankTransactionStatus', 'payrollController@updatePayrollBankTransactionStatus')->name('updatePayrollBankTransactionStatus');
});
Route::get('/payment/{token}','FormController@showAmount')->name('publicForm');
Auth::routes();

app/Location.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    public function policies(){
        return $this->belongsToMany('App\Policy')->withPivot('id');
    }

}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use App\Location;
use App\Policy;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class LocationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user=Auth::user();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'View Location', $user->location_id);
        if($isAllowed){

//        $slelcted_loaction = session()->get('selected_location_id');
        $current_location = "Admin";
//        if ($slelcted_loaction != null) {
//            $loc = Location::where('id', $slelcted_loaction)->first();
//            $current_location = $loc->name;


            $locations = Location::all();
            return view('location.index', compact('locations', 'current_location'));

        }else{
            return redirect(route('dashboard'))->with(['Message','You Dont have Permission to access']);
        }
    }

        public function ajaxdata(Request $request){
            $data = Location::where('id', '>', 0);
            return DataTables::of($data)
                ->addColumn('function', function (Location $location) {
                    return "<a href='". route('location.edit', $location->id)."' id='edit'>
                        <button class='btn btn-primary' title='Edit' data-toggle='modal' data-target=''><i class='fa fa-edit'></i></button></a>" . view('location.delete', compact('location'))->render();
                })
                ->rawColumns(['function'])
                ->make(true);
        }
    public function setLocation(Request $request)
    {
        $request->session()->put('selected_location_id', $request->location);

        return redirect('location');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user=Auth::user();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'Create Location', $user->location_id);
        if($isAllowed){
            return view('location.create');
        }else{
            return redirect(route('dashboard'))->with(['Message','You Dont have Permission to access']);
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $request->validate([
            'name' => 'required|',
            'address' => 'required',
        ]);
        $location = new  Location();
        $location->name = $request->name;
        $location->address = $request->address;
        $location->save();
        $policies = Policy::all();
        $location->policies()->sync($policies);
        return redirect()->back()->with(['message'=>'Location Updated Successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Location $location)
    {
        $user=Auth::user();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'Edit Location', $user->location_id);
        if($isAllowed){
            return view ('location.edit',compact('location'));
        }else{
            return redirect(route('dashboard'))->with(['Message','You Dont have Permission to access']);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Location $location)
    {
        $location->name = $request->name;
        $location->address = $request->address;
        $location->save();
        return redirect()->back()->with(['message'=>'Location Updated Successfully.']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Location $location)
    {
        $user=Auth::user();
        $user->load('roles');
        $isAllowed = MyCheck::check($user, 'Delete Location', $user->location_id);
        if($isAllowed){
            $location->delete();
            return redirect()->back()->with(['message'=>'Location Deleted Successfully.']);
        }else{
            return redirect(route('dashboard'))->with(['Message','You Dont have Permission to access']);
        }
    }
//    public function delete(Request $request, Location $location){
//        $user=Auth::user();
//        $user->load('roles');
//        $isAllowed = MyCheck::check($user, 'formview', $location);
////        return $isAllowed;
//        if($isAllowed){
//            return 'yeah fuck it';
//        }else{
//            return 'you cant delete it motherfucker';
//        }
//    }
}

resources/views/location/create.blade.php
@extends('master')
@section('content')
    <div class="card">

        <div class="row">
            <div class="col-md-12">
                <div class="card bg-gray-light ">
                    <div class="card-header text-black anime">
                        <p class="text-black-50">Create Location</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            @if(session()->has('message'))
                                <div class="alert alert-success">
                                    {{ session()->get('message') }}
                                </div>
                            @endif
                            <form action="{{route('location.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                                @method('POST')
                                <div class="form-group">
                                <label>Name</label>
                                    <div class="col-md-6">
                                    <input class="form-control" name="name" type="text"  value="{{ old('name') }}">
                                </div>
                                </div>
                                <div class="form-group">
                                    <label>Address</label>
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" name="address" value="{{ old('address') }}">
                                    </div>
                                </div>

                                <input type="submit" class="btn btn-lg btn-primary">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/location/delete.blade.php
<button class="btn btn-danger" onclick="frmdlt{{$location->id}}.submit();"  title="Block"><i class="fa fa-ban"></i></button>
<form name="frmdlt{{$location->id}}" action="{{ route('location.destroy', $location->id)}}" method="post">
    {!! method_field('delete') !!}
    {{csrf_field()}}
</form>

resources/views/location/edit.blade.php
@extends('master')
@section('content')
    <div class="card">
        <div class="row">
            <div class="col-md-12">
                <div class="card bg-gray-light ">
                    <div class="card-header text-black anime">
                        <p class="text-black-50">Create Location</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            @if(session()->has('message'))
                                <div class="alert alert-success">
                                    {{ session()->get('message') }}
                                </div>
                            @endif
                            <form action="{{route('location.update',$location->id)}}" method="post" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label>Name</label>
                                    <div class="col-md-6">
                                        <input class="form-control" name="name" type="text"  value="{{ old('name',$location->name) }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Address</label>
                                    <div class="col-md-6">
                                        <input class="form-control" type="text" name="address" value="{{ old('address',$location->address) }}">
                                    </div>
                                </div>

                                <input type="submit" class="btn btn-lg btn-primary">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/location/index.blade.php
@extends('master')
@section('content')
    <div class="card">

        <div class="row">
            <div class="col-md-12">
                <div class="card bg-gray-light ">
                    <div class="card-header text-black anime">
                        <p class="text-black-50">Users Details</p>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="data"  class="table-striped"
                                   style="width: 90%;">
                                <thead>
                                <tr class="bg-pale-dark">
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Functions</th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $('#data').DataTable({
                dom: 'lBtip',
                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
                processing: true,
                serverSide: true,
                responsive: true,
                scrollX: true,
                ajax: {
                    url: '{{route('ajaxdata')}}',
                },
                columns: [
                    {data: 'id', Title: 'id', orderable: false},
                    {data: 'name', Title: 'name', orderable: false},
                    {data: 'address', Title: 'address', orderable: false},
                    {data: 'function', Title: 'function', orderable: false},
                ],
            });
        });




    </script>
@endsection

resources/views/location/view.blade.php
@extends('master')
@section('content')
<div class="card">

    <div class="row">
        <div class="col-md-12">
            <div class="card bg-gray-light ">
                <div class="card-header text-black anime">
                    <p class="text-black-50">Select Current Location</p><br>
                    <p class="text-black-50">Currently Selected: <b>{{$current_location}}</b></p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <form action="{{route('set_location')}}">
                            @csrf
                            @method('GET')
                            <div class="form-group">
                                <label>Select Current Location</label>
                                <div class="col-md-6">
                                    <select name="location" id="" class="form-control">
                                        @foreach($locations as $location)
                                            <option value="{{$location->id}}">{{$location->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-lg btn-primary">Save Location</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection